version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend-docker
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    restart: unless-stopped

  postgres:
    image: postgres:15.3-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./pg-data:/var/lib/postgresql/testtask/pgdata
    restart: always
    environment:
      - POSTGRES_PASSWORD=student
      - POSTGRES_USER=student
      - POSTGRES_DB=nest_project
